[build-system]
requires = ["flit_core >=3.2,<4", "setuptools>=58", "wheel"]
build-backend = "flit_core.buildapi"

[project]
name = "fgem"
authors = [{name = "Mohammad Aljubran", email = "aljubrmj@stanford.edu"}]
dynamic = ["version", "description"]
